use super::cpu::Cpu;
use log::{debug, warn};

// Format string representation
fn to_string(opcode: u8, mnemonic: &str, operands: &str) -> String {
    format!("| {:02X} - {:<10} | {:<5} |", opcode, mnemonic, operands)
}

// Get the operands of the instruction from memory as a String
fn get_operands(cpu: &Cpu, len: u8) -> String {
    let mut operands = String::new();
    for i in 1..len {
        operands.push_str(&format!("{:02X} ", cpu.mmu.get(cpu.reg.pc + i as u16)));
    }
    operands.pop(); // Remove the trailing space if it exists
    operands
}

// Unknown opcode
fn unknown(cpu: &Cpu) -> String {
    format!("| {:02X} - {} | Unknown opcode |", cpu.opcode, "???")
}

// Log the decoded opcode appropriately
pub fn log_decode(cpu: &Cpu) {
    if let Some(decoded) = decode(cpu) {
        debug!("{}", decoded);
    } else {
        warn!("{}", unknown(cpu));
    }
}

// Match the opcode and return a formatted String, else return None
pub fn decode(cpu: &Cpu) -> Option<String> {
    match cpu.opcode {
        0x00 => Some(to_string(0x00, "NOP ", &get_operands(cpu, 1))),
        0x01 => Some(to_string(0x01, "LD BC d16", &get_operands(cpu, 3))),
        0x02 => Some(to_string(0x02, "LD (BC) A", &get_operands(cpu, 1))),
        0x03 => Some(to_string(0x03, "INC BC ", &get_operands(cpu, 1))),
        0x04 => Some(to_string(0x04, "INC B ", &get_operands(cpu, 1))),
        0x05 => Some(to_string(0x05, "DEC B ", &get_operands(cpu, 1))),
        0x06 => Some(to_string(0x06, "LD B d8", &get_operands(cpu, 2))),
        0x07 => Some(to_string(0x07, "RLCA ", &get_operands(cpu, 1))),
        0x08 => Some(to_string(0x08, "LD (a16) SP", &get_operands(cpu, 3))),
        0x09 => Some(to_string(0x09, "ADD HL BC", &get_operands(cpu, 1))),
        0x0a => Some(to_string(0x0a, "LD A (BC)", &get_operands(cpu, 1))),
        0x0b => Some(to_string(0x0b, "DEC BC ", &get_operands(cpu, 1))),
        0x0c => Some(to_string(0x0c, "INC C ", &get_operands(cpu, 1))),
        0x0d => Some(to_string(0x0d, "DEC C ", &get_operands(cpu, 1))),
        0x0e => Some(to_string(0x0e, "LD C d8", &get_operands(cpu, 2))),
        0x0f => Some(to_string(0x0f, "RRCA ", &get_operands(cpu, 1))),
        0x10 => Some(to_string(0x10, "STOP 0 ", &get_operands(cpu, 1))),
        0x11 => Some(to_string(0x11, "LD DE d16", &get_operands(cpu, 3))),
        0x12 => Some(to_string(0x12, "LD (DE) A", &get_operands(cpu, 1))),
        0x13 => Some(to_string(0x13, "INC DE ", &get_operands(cpu, 1))),
        0x14 => Some(to_string(0x14, "INC D ", &get_operands(cpu, 1))),
        0x15 => Some(to_string(0x15, "DEC D ", &get_operands(cpu, 1))),
        0x16 => Some(to_string(0x16, "LD D d8", &get_operands(cpu, 2))),
        0x17 => Some(to_string(0x17, "RLA ", &get_operands(cpu, 1))),
        0x18 => Some(to_string(0x18, "JR r8 ", &get_operands(cpu, 2))),
        0x19 => Some(to_string(0x19, "ADD HL DE", &get_operands(cpu, 1))),
        0x1a => Some(to_string(0x1a, "LD A (DE)", &get_operands(cpu, 1))),
        0x1b => Some(to_string(0x1b, "DEC DE ", &get_operands(cpu, 1))),
        0x1c => Some(to_string(0x1c, "INC E ", &get_operands(cpu, 1))),
        0x1d => Some(to_string(0x1d, "DEC E ", &get_operands(cpu, 1))),
        0x1e => Some(to_string(0x1e, "LD E d8", &get_operands(cpu, 2))),
        0x1f => Some(to_string(0x1f, "RRA ", &get_operands(cpu, 1))),
        0x20 => Some(to_string(0x20, "JR NZ r8", &get_operands(cpu, 2))),
        0x21 => Some(to_string(0x21, "LD HL d16", &get_operands(cpu, 3))),
        0x22 => Some(to_string(0x22, "LD (HL+) A", &get_operands(cpu, 1))),
        0x23 => Some(to_string(0x23, "INC HL ", &get_operands(cpu, 1))),
        0x24 => Some(to_string(0x24, "INC H ", &get_operands(cpu, 1))),
        0x25 => Some(to_string(0x25, "DEC H ", &get_operands(cpu, 1))),
        0x26 => Some(to_string(0x26, "LD H d8", &get_operands(cpu, 2))),
        0x27 => Some(to_string(0x27, "DAA ", &get_operands(cpu, 1))),
        0x28 => Some(to_string(0x28, "JR Z r8", &get_operands(cpu, 2))),
        0x29 => Some(to_string(0x29, "ADD HL HL", &get_operands(cpu, 1))),
        0x2a => Some(to_string(0x2a, "LD A (HL+)", &get_operands(cpu, 1))),
        0x2b => Some(to_string(0x2b, "DEC HL ", &get_operands(cpu, 1))),
        0x2c => Some(to_string(0x2c, "INC L ", &get_operands(cpu, 1))),
        0x2d => Some(to_string(0x2d, "DEC L ", &get_operands(cpu, 1))),
        0x2e => Some(to_string(0x2e, "LD L d8", &get_operands(cpu, 2))),
        0x2f => Some(to_string(0x2f, "CPL ", &get_operands(cpu, 1))),
        0x30 => Some(to_string(0x30, "JR NC r8", &get_operands(cpu, 2))),
        0x31 => Some(to_string(0x31, "LD SP d16", &get_operands(cpu, 3))),
        0x32 => Some(to_string(0x32, "LD (HL-) A", &get_operands(cpu, 1))),
        0x33 => Some(to_string(0x33, "INC SP ", &get_operands(cpu, 1))),
        0x34 => Some(to_string(0x34, "INC (HL) ", &get_operands(cpu, 1))),
        0x35 => Some(to_string(0x35, "DEC (HL) ", &get_operands(cpu, 1))),
        0x36 => Some(to_string(0x36, "LD (HL) d8", &get_operands(cpu, 2))),
        0x37 => Some(to_string(0x37, "SCF ", &get_operands(cpu, 1))),
        0x38 => Some(to_string(0x38, "JR C r8", &get_operands(cpu, 2))),
        0x39 => Some(to_string(0x39, "ADD HL SP", &get_operands(cpu, 1))),
        0x3a => Some(to_string(0x3a, "LD A (HL-)", &get_operands(cpu, 1))),
        0x3b => Some(to_string(0x3b, "DEC SP ", &get_operands(cpu, 1))),
        0x3c => Some(to_string(0x3c, "INC A ", &get_operands(cpu, 1))),
        0x3d => Some(to_string(0x3d, "DEC A ", &get_operands(cpu, 1))),
        0x3e => Some(to_string(0x3e, "LD A d8", &get_operands(cpu, 2))),
        0x3f => Some(to_string(0x3f, "CCF ", &get_operands(cpu, 1))),
        0x40 => Some(to_string(0x40, "LD B B", &get_operands(cpu, 1))),
        0x41 => Some(to_string(0x41, "LD B C", &get_operands(cpu, 1))),
        0x42 => Some(to_string(0x42, "LD B D", &get_operands(cpu, 1))),
        0x43 => Some(to_string(0x43, "LD B E", &get_operands(cpu, 1))),
        0x44 => Some(to_string(0x44, "LD B H", &get_operands(cpu, 1))),
        0x45 => Some(to_string(0x45, "LD B L", &get_operands(cpu, 1))),
        0x46 => Some(to_string(0x46, "LD B (HL)", &get_operands(cpu, 1))),
        0x47 => Some(to_string(0x47, "LD B A", &get_operands(cpu, 1))),
        0x48 => Some(to_string(0x48, "LD C B", &get_operands(cpu, 1))),
        0x49 => Some(to_string(0x49, "LD C C", &get_operands(cpu, 1))),
        0x4a => Some(to_string(0x4a, "LD C D", &get_operands(cpu, 1))),
        0x4b => Some(to_string(0x4b, "LD C E", &get_operands(cpu, 1))),
        0x4c => Some(to_string(0x4c, "LD C H", &get_operands(cpu, 1))),
        0x4d => Some(to_string(0x4d, "LD C L", &get_operands(cpu, 1))),
        0x4e => Some(to_string(0x4e, "LD C (HL)", &get_operands(cpu, 1))),
        0x4f => Some(to_string(0x4f, "LD C A", &get_operands(cpu, 1))),
        0x50 => Some(to_string(0x50, "LD D B", &get_operands(cpu, 1))),
        0x51 => Some(to_string(0x51, "LD D C", &get_operands(cpu, 1))),
        0x52 => Some(to_string(0x52, "LD D D", &get_operands(cpu, 1))),
        0x53 => Some(to_string(0x53, "LD D E", &get_operands(cpu, 1))),
        0x54 => Some(to_string(0x54, "LD D H", &get_operands(cpu, 1))),
        0x55 => Some(to_string(0x55, "LD D L", &get_operands(cpu, 1))),
        0x56 => Some(to_string(0x56, "LD D (HL)", &get_operands(cpu, 1))),
        0x57 => Some(to_string(0x57, "LD D A", &get_operands(cpu, 1))),
        0x58 => Some(to_string(0x58, "LD E B", &get_operands(cpu, 1))),
        0x59 => Some(to_string(0x59, "LD E C", &get_operands(cpu, 1))),
        0x5a => Some(to_string(0x5a, "LD E D", &get_operands(cpu, 1))),
        0x5b => Some(to_string(0x5b, "LD E E", &get_operands(cpu, 1))),
        0x5c => Some(to_string(0x5c, "LD E H", &get_operands(cpu, 1))),
        0x5d => Some(to_string(0x5d, "LD E L", &get_operands(cpu, 1))),
        0x5e => Some(to_string(0x5e, "LD E (HL)", &get_operands(cpu, 1))),
        0x5f => Some(to_string(0x5f, "LD E A", &get_operands(cpu, 1))),
        0x60 => Some(to_string(0x60, "LD H B", &get_operands(cpu, 1))),
        0x61 => Some(to_string(0x61, "LD H C", &get_operands(cpu, 1))),
        0x62 => Some(to_string(0x62, "LD H D", &get_operands(cpu, 1))),
        0x63 => Some(to_string(0x63, "LD H E", &get_operands(cpu, 1))),
        0x64 => Some(to_string(0x64, "LD H H", &get_operands(cpu, 1))),
        0x65 => Some(to_string(0x65, "LD H L", &get_operands(cpu, 1))),
        0x66 => Some(to_string(0x66, "LD H (HL)", &get_operands(cpu, 1))),
        0x67 => Some(to_string(0x67, "LD H A", &get_operands(cpu, 1))),
        0x68 => Some(to_string(0x68, "LD L B", &get_operands(cpu, 1))),
        0x69 => Some(to_string(0x69, "LD L C", &get_operands(cpu, 1))),
        0x6a => Some(to_string(0x6a, "LD L D", &get_operands(cpu, 1))),
        0x6b => Some(to_string(0x6b, "LD L E", &get_operands(cpu, 1))),
        0x6c => Some(to_string(0x6c, "LD L H", &get_operands(cpu, 1))),
        0x6d => Some(to_string(0x6d, "LD L L", &get_operands(cpu, 1))),
        0x6e => Some(to_string(0x6e, "LD L (HL)", &get_operands(cpu, 1))),
        0x6f => Some(to_string(0x6f, "LD L A", &get_operands(cpu, 1))),
        0x70 => Some(to_string(0x70, "LD (HL) B", &get_operands(cpu, 1))),
        0x71 => Some(to_string(0x71, "LD (HL) C", &get_operands(cpu, 1))),
        0x72 => Some(to_string(0x72, "LD (HL) D", &get_operands(cpu, 1))),
        0x73 => Some(to_string(0x73, "LD (HL) E", &get_operands(cpu, 1))),
        0x74 => Some(to_string(0x74, "LD (HL) H", &get_operands(cpu, 1))),
        0x75 => Some(to_string(0x75, "LD (HL) L", &get_operands(cpu, 1))),
        0x76 => Some(to_string(0x76, "HALT ", &get_operands(cpu, 1))),
        0x77 => Some(to_string(0x77, "LD (HL) A", &get_operands(cpu, 1))),
        0x78 => Some(to_string(0x78, "LD A B", &get_operands(cpu, 1))),
        0x79 => Some(to_string(0x79, "LD A C", &get_operands(cpu, 1))),
        0x7a => Some(to_string(0x7a, "LD A D", &get_operands(cpu, 1))),
        0x7b => Some(to_string(0x7b, "LD A E", &get_operands(cpu, 1))),
        0x7c => Some(to_string(0x7c, "LD A H", &get_operands(cpu, 1))),
        0x7d => Some(to_string(0x7d, "LD A L", &get_operands(cpu, 1))),
        0x7e => Some(to_string(0x7e, "LD A (HL)", &get_operands(cpu, 1))),
        0x7f => Some(to_string(0x7f, "LD A A", &get_operands(cpu, 1))),
        0x80 => Some(to_string(0x80, "ADD A B", &get_operands(cpu, 1))),
        0x81 => Some(to_string(0x81, "ADD A C", &get_operands(cpu, 1))),
        0x82 => Some(to_string(0x82, "ADD A D", &get_operands(cpu, 1))),
        0x83 => Some(to_string(0x83, "ADD A E", &get_operands(cpu, 1))),
        0x84 => Some(to_string(0x84, "ADD A H", &get_operands(cpu, 1))),
        0x85 => Some(to_string(0x85, "ADD A L", &get_operands(cpu, 1))),
        0x86 => Some(to_string(0x86, "ADD A (HL)", &get_operands(cpu, 1))),
        0x87 => Some(to_string(0x87, "ADD A A", &get_operands(cpu, 1))),
        0x88 => Some(to_string(0x88, "ADC A B", &get_operands(cpu, 1))),
        0x89 => Some(to_string(0x89, "ADC A C", &get_operands(cpu, 1))),
        0x8a => Some(to_string(0x8a, "ADC A D", &get_operands(cpu, 1))),
        0x8b => Some(to_string(0x8b, "ADC A E", &get_operands(cpu, 1))),
        0x8c => Some(to_string(0x8c, "ADC A H", &get_operands(cpu, 1))),
        0x8d => Some(to_string(0x8d, "ADC A L", &get_operands(cpu, 1))),
        0x8e => Some(to_string(0x8e, "ADC A (HL)", &get_operands(cpu, 1))),
        0x8f => Some(to_string(0x8f, "ADC A A", &get_operands(cpu, 1))),
        0x90 => Some(to_string(0x90, "SUB B ", &get_operands(cpu, 1))),
        0x91 => Some(to_string(0x91, "SUB C ", &get_operands(cpu, 1))),
        0x92 => Some(to_string(0x92, "SUB D ", &get_operands(cpu, 1))),
        0x93 => Some(to_string(0x93, "SUB E ", &get_operands(cpu, 1))),
        0x94 => Some(to_string(0x94, "SUB H ", &get_operands(cpu, 1))),
        0x95 => Some(to_string(0x95, "SUB L ", &get_operands(cpu, 1))),
        0x96 => Some(to_string(0x96, "SUB (HL) ", &get_operands(cpu, 1))),
        0x97 => Some(to_string(0x97, "SUB A ", &get_operands(cpu, 1))),
        0x98 => Some(to_string(0x98, "SBC A B", &get_operands(cpu, 1))),
        0x99 => Some(to_string(0x99, "SBC A C", &get_operands(cpu, 1))),
        0x9a => Some(to_string(0x9a, "SBC A D", &get_operands(cpu, 1))),
        0x9b => Some(to_string(0x9b, "SBC A E", &get_operands(cpu, 1))),
        0x9c => Some(to_string(0x9c, "SBC A H", &get_operands(cpu, 1))),
        0x9d => Some(to_string(0x9d, "SBC A L", &get_operands(cpu, 1))),
        0x9e => Some(to_string(0x9e, "SBC A (HL)", &get_operands(cpu, 1))),
        0x9f => Some(to_string(0x9f, "SBC A A", &get_operands(cpu, 1))),
        0xa0 => Some(to_string(0xa0, "AND B ", &get_operands(cpu, 1))),
        0xa1 => Some(to_string(0xa1, "AND C ", &get_operands(cpu, 1))),
        0xa2 => Some(to_string(0xa2, "AND D ", &get_operands(cpu, 1))),
        0xa3 => Some(to_string(0xa3, "AND E ", &get_operands(cpu, 1))),
        0xa4 => Some(to_string(0xa4, "AND H ", &get_operands(cpu, 1))),
        0xa5 => Some(to_string(0xa5, "AND L ", &get_operands(cpu, 1))),
        0xa6 => Some(to_string(0xa6, "AND (HL) ", &get_operands(cpu, 1))),
        0xa7 => Some(to_string(0xa7, "AND A ", &get_operands(cpu, 1))),
        0xa8 => Some(to_string(0xa8, "XOR B ", &get_operands(cpu, 1))),
        0xa9 => Some(to_string(0xa9, "XOR C ", &get_operands(cpu, 1))),
        0xaa => Some(to_string(0xaa, "XOR D ", &get_operands(cpu, 1))),
        0xab => Some(to_string(0xab, "XOR E ", &get_operands(cpu, 1))),
        0xac => Some(to_string(0xac, "XOR H ", &get_operands(cpu, 1))),
        0xad => Some(to_string(0xad, "XOR L ", &get_operands(cpu, 1))),
        0xae => Some(to_string(0xae, "XOR (HL) ", &get_operands(cpu, 1))),
        0xaf => Some(to_string(0xaf, "XOR A ", &get_operands(cpu, 1))),
        0xb0 => Some(to_string(0xb0, "OR B ", &get_operands(cpu, 1))),
        0xb1 => Some(to_string(0xb1, "OR C ", &get_operands(cpu, 1))),
        0xb2 => Some(to_string(0xb2, "OR D ", &get_operands(cpu, 1))),
        0xb3 => Some(to_string(0xb3, "OR E ", &get_operands(cpu, 1))),
        0xb4 => Some(to_string(0xb4, "OR H ", &get_operands(cpu, 1))),
        0xb5 => Some(to_string(0xb5, "OR L ", &get_operands(cpu, 1))),
        0xb6 => Some(to_string(0xb6, "OR (HL) ", &get_operands(cpu, 1))),
        0xb7 => Some(to_string(0xb7, "OR A ", &get_operands(cpu, 1))),
        0xb8 => Some(to_string(0xb8, "CP B ", &get_operands(cpu, 1))),
        0xb9 => Some(to_string(0xb9, "CP C ", &get_operands(cpu, 1))),
        0xba => Some(to_string(0xba, "CP D ", &get_operands(cpu, 1))),
        0xbb => Some(to_string(0xbb, "CP E ", &get_operands(cpu, 1))),
        0xbc => Some(to_string(0xbc, "CP H ", &get_operands(cpu, 1))),
        0xbd => Some(to_string(0xbd, "CP L ", &get_operands(cpu, 1))),
        0xbe => Some(to_string(0xbe, "CP (HL) ", &get_operands(cpu, 1))),
        0xbf => Some(to_string(0xbf, "CP A ", &get_operands(cpu, 1))),
        0xc0 => Some(to_string(0xc0, "RET NZ ", &get_operands(cpu, 1))),
        0xc1 => Some(to_string(0xc1, "POP BC ", &get_operands(cpu, 1))),
        0xc2 => Some(to_string(0xc2, "JP NZ a16", &get_operands(cpu, 3))),
        0xc3 => Some(to_string(0xc3, "JP a16 ", &get_operands(cpu, 3))),
        0xc4 => Some(to_string(0xc4, "CALL NZ a16", &get_operands(cpu, 3))),
        0xc5 => Some(to_string(0xc5, "PUSH BC ", &get_operands(cpu, 1))),
        0xc6 => Some(to_string(0xc6, "ADD A d8", &get_operands(cpu, 2))),
        0xc7 => Some(to_string(0xc7, "RST 00H ", &get_operands(cpu, 1))),
        0xc8 => Some(to_string(0xc8, "RET Z ", &get_operands(cpu, 1))),
        0xc9 => Some(to_string(0xc9, "RET ", &get_operands(cpu, 1))),
        0xca => Some(to_string(0xca, "JP Z a16", &get_operands(cpu, 3))),
        0xcb => Some(to_string(0xcb, "PREFIX CB ", &get_operands(cpu, 1))),
        0xcc => Some(to_string(0xcc, "CALL Z a16", &get_operands(cpu, 3))),
        0xcd => Some(to_string(0xcd, "CALL a16 ", &get_operands(cpu, 3))),
        0xce => Some(to_string(0xce, "ADC A d8", &get_operands(cpu, 2))),
        0xcf => Some(to_string(0xcf, "RST 08H ", &get_operands(cpu, 1))),
        0xd0 => Some(to_string(0xd0, "RET NC ", &get_operands(cpu, 1))),
        0xd1 => Some(to_string(0xd1, "POP DE ", &get_operands(cpu, 1))),
        0xd2 => Some(to_string(0xd2, "JP NC a16", &get_operands(cpu, 3))),
        0xd4 => Some(to_string(0xd4, "CALL NC a16", &get_operands(cpu, 3))),
        0xd5 => Some(to_string(0xd5, "PUSH DE ", &get_operands(cpu, 1))),
        0xd6 => Some(to_string(0xd6, "SUB d8 ", &get_operands(cpu, 2))),
        0xd7 => Some(to_string(0xd7, "RST 10H ", &get_operands(cpu, 1))),
        0xd8 => Some(to_string(0xd8, "RET C ", &get_operands(cpu, 1))),
        0xd9 => Some(to_string(0xd9, "RETI ", &get_operands(cpu, 1))),
        0xda => Some(to_string(0xda, "JP C a16", &get_operands(cpu, 3))),
        0xdc => Some(to_string(0xdc, "CALL C a16", &get_operands(cpu, 3))),
        0xde => Some(to_string(0xde, "SBC A d8", &get_operands(cpu, 2))),
        0xdf => Some(to_string(0xdf, "RST 18H ", &get_operands(cpu, 1))),
        0xe0 => Some(to_string(0xe0, "LDH (a8) A", &get_operands(cpu, 2))),
        0xe1 => Some(to_string(0xe1, "POP HL ", &get_operands(cpu, 1))),
        0xe2 => Some(to_string(0xe2, "LD (C) A", &get_operands(cpu, 1))),
        0xe5 => Some(to_string(0xe5, "PUSH HL ", &get_operands(cpu, 1))),
        0xe6 => Some(to_string(0xe6, "AND d8 ", &get_operands(cpu, 2))),
        0xe7 => Some(to_string(0xe7, "RST 20H ", &get_operands(cpu, 1))),
        0xe8 => Some(to_string(0xe8, "ADD SP r8", &get_operands(cpu, 2))),
        0xe9 => Some(to_string(0xe9, "JP (HL) ", &get_operands(cpu, 1))),
        0xea => Some(to_string(0xea, "LD (a16) A", &get_operands(cpu, 3))),
        0xee => Some(to_string(0xee, "XOR d8 ", &get_operands(cpu, 2))),
        0xef => Some(to_string(0xef, "RST 28H ", &get_operands(cpu, 1))),
        0xf0 => Some(to_string(0xf0, "LDH A (a8)", &get_operands(cpu, 2))),
        0xf1 => Some(to_string(0xf1, "POP AF ", &get_operands(cpu, 1))),
        0xf2 => Some(to_string(0xf2, "LD A (C)", &get_operands(cpu, 1))),
        0xf3 => Some(to_string(0xf3, "DI ", &get_operands(cpu, 1))),
        0xf5 => Some(to_string(0xf5, "PUSH AF ", &get_operands(cpu, 1))),
        0xf6 => Some(to_string(0xf6, "OR d8 ", &get_operands(cpu, 2))),
        0xf7 => Some(to_string(0xf7, "RST 30H ", &get_operands(cpu, 1))),
        0xf8 => Some(to_string(0xf8, "LD HL SP+r8", &get_operands(cpu, 2))),
        0xf9 => Some(to_string(0xf9, "LD SP HL", &get_operands(cpu, 1))),
        0xfa => Some(to_string(0xfa, "LD A (a16)", &get_operands(cpu, 3))),
        0xfb => Some(to_string(0xfb, "EI ", &get_operands(cpu, 1))),
        0xfe => Some(to_string(0xfe, "CP d8 ", &get_operands(cpu, 2))),
        0xff => Some(to_string(0xff, "RST 38H ", &get_operands(cpu, 1))),
        _ => None
    }
}
